### ISSUE TITLE
Clean UP & Dockerization eos44zp

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos44zp#4]
Please refactor this model to work with the latest structure of the template

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron 
Yes, i'm working on it.

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron 
I have made PR on this mode. Kindly have a look.
Thanks.

**Comment by GemmaTuron** [comment]
@ZakiaYahya 
The Test is failing, please revise

**Comment by ZakiaYahya** [comment]
Okay @GemmaTuron 
I'll check it again.

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron 
I run it again, check the workflows everythings seems fine to me. Model is working both locally and inside ersilia --rep_path as well, here's the output file

[eos44zp_Out.csv](https://github.com/ersilia-os/eos44zp/files/11816540/eos44zp_Out.csv)

should i push the repo and made PR on it again?? what you suggests??

**Comment by GemmaTuron** [comment]
is there any change on the PR from what is in the repo now?

**Comment by ZakiaYahya** [comment]
@GemmaTuron 
Nope, i just put the latest workflows in it

**Comment by GemmaTuron** [comment]
Hi @ZakiaYahya 

Please next time when a workflow fails try to identify the source of the error. If you go to the failed Action and look through it you'll identify the cause of the error:
ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device
I do not know what is the Git Action space allocation, this model is quite heavy

**Comment by ZakiaYahya** [comment]
Hi @GemmaTuron 
Yes, i've gone through the git Actions and it failed at `ModelPackageInstallError` and i thought there is some problem with the packages defined in the `Dockerfile` that's why i test it again in a new conda environment. Yes, it's a heavy model as it took alot more time in giving prediction even for 9 smiles strings. But next time i'll try to dig in more detail.
Thanks.

**Comment by GemmaTuron** [comment]
The ModelPackageInstallError is a default Error, even if it is a specific package that is failing you'll need to go through the lines of the log file to identify which specific package is not being installed, in this case all because there was no space. I'll try to manually run the dockerhub build but I am unsure if we'll be able to. If that is the case, we'll do it manually from our system.
Could you confirm that the model works also with .csv outputs?

**Comment by ZakiaYahya** [comment]
Right @GemmaTuron 
Thanks for pointing it out. Yes, i have passed a csv file of 9 smile strings and it gave me output.

**Comment by GemmaTuron** [comment]
@miquelduranfrigola 
We have reached a model that works but does not pass the tests because it might be too big for Git Actions? which is our limit there, is there a way to bypass it?

**Comment by GemmaTuron** [comment]
seems that we have about 10 GB? https://github.blog/changelog/2021-11-23-github-actions-cache-size-is-now-increased-to-10gb-per-repository/

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron @miquelduranfrigola @DhanshreeA 
I have few questions and i need your assistance here

(1) Is there anyway to check the memory of github-runners allocated to ersilia  (bcoz i don't know which type of Github 
     are you using, either public or private or it's enterprise level). In this link 
     https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners 
     it is showing 7GB RAM and i read somewhere it's generally recommended to allocate swap space of 1-2 times the 
     available physical memory to mitigate space issues during workflow execution. 

(2) Plus i've added Swap-Space code in `"test-model.yaml"`, Is that the correct file where we need to do this 
     modification?

(3) Do we need hit-and-trial method to check how much swap-space we required to resolve the issue if we doesn't get 
     any idea about the memory allocated to github-runners?

Thanks.

**Comment by GemmaTuron** [comment]
Hi @ZakiaYahya 

Thanks for these detailed summary and questions. I think according to the GitHub link you shared, we have allocated 7GB of RAM, so we should allocate up to 14GB for swap. The modification in test-model is the right one, since this will trigger the rest of the tests. If you are ready, open a PR and we'll test it!

**Comment by ZakiaYahya** [comment]
Thanks @GemmaTuron 
I've added swap-space of 14GB in `test-model.yml` file. I've open PR on it, kindly check it whether it is working or not.

**Comment by GemmaTuron** [comment]
It seems like the swap is not doing the trick

**Comment by ZakiaYahya** [comment]
Hi @GemmaTuron 
I think we should try 7GB or 10GB, what you say?

**Comment by GemmaTuron** [comment]
Hi @ZakiaYahya 

Sorry I do not follow, we tried 14 GB and it did not work, so 7 or 10 why?

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron @miquelduranfrigola @DhanshreeA 
Because in some forums it says that github increases the size to 10GB that's why i'm saying to test with 10GB swap-size. Otherwise  we can try this as well 
```

name: Free Disk Space (Ubuntu)
on: push

jobs:
  free-disk-space:
    runs-on: ubuntu-latest
    steps:

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # when set to "true" but frees about 6 GB
        tool-cache: true
        
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true
```
In this code we can set `tool-cache` to `false` so that it won't delete python that we needed in our case. Kindly guide me on this as you have much better knowlegde than me.
Thanks

**Comment by GemmaTuron** [comment]
Hi @ZakiaYahya 

I don't know that much about Git Actions so we can try the options you suggest, do you want to test first the 10 GB?
open a PR and i'll merge it

**Comment by ZakiaYahya** [comment]
Right @GemmaTuron 
I think we should incorporate both 10GB swap size thing and deleting packages like    
```
        dotnet: true
        haskell: true
        large-packages: true 
```
keeping` tool-cache` to` false` and `swap-storage `to `true` . I think we should give it a try atleast before tomorrow's meeting so we can discuss it if it doesn't work.
I'll do the necessary changes and then open PR on it.
Thanks.

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron 
I've incorporate the changes i.e. adding `swap-space` plus `deleting some of tools` as well and open PR on it but it failed at 
`Model Test on PR` https://github.com/ersilia-os/eos44zp/actions/runs/5446582694/jobs/9907530334?pr=7 with the same error `No space left on device`
From this it seems like both workarounds didn't fix the problem.

**Comment by GemmaTuron** [comment]
Hi @ZakiaYahya 
The model test on PR will use the existing workflows in the repository, so I don't think we would see the changes. I've merged it, let's see!

**Comment by ZakiaYahya** [comment]
Oh right, got it.
Let's see, hope it will work.
Thanks

**Comment by GemmaTuron** [comment]
Hi @ZakiaYahya 

Could it be that we activate the swap space but that it is not being used?
This is what is shown:
```
NAME          TYPE SIZE USED PRIO
/mnt/swapfile file  10G   0B   -2
```
Is there a way to print where is Git Actions storing the data?

**Comment by ZakiaYahya** [comment]
Oh okay, 
i just searched on it and it says that we can do it by using this piece of code in yml file

```
jobs:
  print-data-location:
    runs-on: ubuntu-latest
    steps:
      - name: Print data location
        run: echo $GITHUB_WORKSPACE
```

Should we do it in `test-model.yml` file??

**Comment by GemmaTuron** [comment]
yes, open a PR and I'll merge regardless of the checks!

**Comment by ZakiaYahya** [comment]
Okay Sure @GemmaTuron 
Keeping the swap-space and tool-cache as well??

**Comment by ZakiaYahya** [comment]
Hi @GemmaTuron 
Mistakenly i've set swap-space to false previously that is why it activated the swap-space but not using it. Now i set it to True. I've open the PR on it again, Kindly check it

**Comment by ZakiaYahya** [comment]
Hello @GemmaTuron 
It again failed at` "Push test"` and giving `You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 0 MB,` here's the log file https://github.com/ersilia-os/eos44zp/actions/runs/5451301826
I'm not getting it why it is not using swap-space, although it shows that we have successfully activated it.  Any Suggestion now??

**Comment by DhanshreeA** [comment]
@GemmaTuron do we know how much SSD storage our github runners have? Maybe someone from the GitHub volunteers could tell us @miquelduranfrigola? Because however much swap space we can actually use depends very much on the size of the persistent storage used by the runner. For example, if the persistent storage size is 14 GB, and the repository is 11GB, then we only have 3GB remaining on the persistent storage (some of which will also be consumed by system files etc). So we need at least double of what we have right now in persistent storage (ie ~30 GB) to increase the swap space to at least 14 GB for it to accommodate both the OS and the models in RAM, and the model repo on disk simultaneously.

**Comment by GemmaTuron** [comment]
We will divide this model in three - @ZakiaYahya

**Comment by miquelduranfrigola** [comment]
> @GemmaTuron do we know how much SSD storage our github runners have? Maybe someone from the GitHub volunteers could tell us @miquelduranfrigola? Because however much swap space we can actually use depends very much on the size of the persistent storage used by the runner. For example, if the persistent storage size is 14 GB, and the repository is 11GB, then we only have 3GB remaining on the persistent storage (some of which will also be consumed by system files etc). So we need at least double of what we have right now in persistent storage (ie ~30 GB) to increase the swap space to at least 14 GB for it to accommodate both the OS and the models in RAM, and the model repo on disk simultaneously.

Great points. In my opinion, the experience with this model also tells me that we should be able to run GitHub Actions workflows locally, whenever we have a need for it. I know this is possible but I have not explored the lanscape.

**Comment by GemmaTuron** [comment]
@honeyankit maybe do you have any idea about extending space in GitHub Actions?

**Comment by GemmaTuron** [comment]
The incorporation of the three CYP models separately is completed, so we can either
- Leave this model as is, jut won't be available through DockerHub
- Archive it to avoid confusions
@miquelduranfrigola what do you prefer? Since it is reported in the ZairaChem publication, I'd leave it as is

**Comment by GemmaTuron** [comment]
I will leave it as is, though it is a duplication I also use it sometimes to get all preds at once.
